WINDOW_TITLE = 'MINICRAFT'
WINDOW_WIDTH = 1280
WINDOW_HIGHT = 720
FULLSCREEN = True
VSYNC = True

CHUNK_SIZE = 16
RENDER_DISTANCE = 2

PLAYER_SPEED = 6.0
PLAYER_JUMP_HIGHT = 1.0 
GRAVITY = 1.0
TEXTURES_DIR = 'assets/textures/'
